import { useEffect, useState } from 'react'
import { X } from 'lucide-react'

const blank = { clientId: '', endpoint: '/api/check', algorithm: 'FIXED_WINDOW_COUNTER', limit: 5, refillRate: 1, windowSize: 60, enabled: true }
export default function RuleModal({ rule, onClose, onSave, saving }) {
  const [form, setForm] = useState(blank); const [error, setError] = useState('')
  useEffect(()=>setForm(rule ? {...rule} : blank), [rule])
  const change=(event)=>{const {name,value,type,checked}=event.target;setForm(p=>({...p,[name]:type==='checkbox'?checked:value}))}
  const submit=(e)=>{e.preventDefault(); if (!form.clientId.trim() || !form.endpoint.trim() || Number(form.limit)<1 || Number(form.refillRate)<1 || Number(form.windowSize)<1) return setError('Fill in all fields with values greater than zero.'); onSave({...form,limit:Number(form.limit),refillRate:Number(form.refillRate),windowSize:Number(form.windowSize)})}
  return <div className="fixed inset-0 z-40 grid place-items-center bg-black/70 p-4"><form onSubmit={submit} className="panel w-full max-w-xl p-6"><div className="mb-5 flex items-center justify-between"><div><h2 className="text-xl font-bold">{rule ? 'Update rate limit rule' : 'Create rate limit rule'}</h2><p className="text-sm text-slate-400">Maps directly to the backend rule API.</p></div><button type="button" onClick={onClose} className="rounded-lg p-2 text-slate-400 hover:bg-slate-800"><X/></button></div><div className="grid gap-4 sm:grid-cols-2"><Field label="Client ID" name="clientId" value={form.clientId} change={change}/><Field label="Endpoint" name="endpoint" value={form.endpoint} change={change}/><div><label className="label">Algorithm</label><select className="input" name="algorithm" value={form.algorithm} onChange={change}><option value="FIXED_WINDOW_COUNTER">Fixed Window</option><option value="SLIDING_WINDOW_LOG">Sliding Window</option><option value="TOKEN_BUCKET">Token Bucket</option></select></div><Field label="Limit" name="limit" type="number" value={form.limit} change={change}/><Field label="Refill rate" name="refillRate" type="number" value={form.refillRate} change={change}/><Field label="Window size (seconds)" name="windowSize" type="number" value={form.windowSize} change={change}/></div><label className="mt-4 flex items-center gap-2 text-sm text-slate-300"><input type="checkbox" name="enabled" checked={form.enabled} onChange={change} className="h-4 w-4 accent-cyan-400"/>Enabled</label>{error && <p className="mt-3 text-sm text-rose-300">{error}</p>}<div className="mt-6 flex justify-end gap-3"><button type="button" className="btn-secondary" onClick={onClose}>Cancel</button><button className="btn-primary" disabled={saving}>{saving ? 'Saving…' : rule ? 'Update Rule' : 'Create Rule'}</button></div></form></div>
}
function Field({label,name,value,change,type='text'}) { return <div><label className="label">{label}</label><input className="input" required min={type==='number'?1:undefined} type={type} name={name} value={value} onChange={change}/></div> }
